Repository Code2Gether-Discord/JokesOnYou, pull requests merged in 2021-04, with the labels that each got.

#69 created appexception
  Server/JokesOnYou.Web.Api/Exceptions/AppException.cs
Labels: backend

#70 fix: remove DeleteUserAsync(int id) from IUserRepository
  Server/JokesOnYou.Web.Api/Repositories/Interfaces/IUserRepository.cs
Labels: bug

#101 split up the ViewedJokes in the architecture diagram.
  Docs/Architecture/ModelArchitectureDiagram-Page-1.png
  Docs/Architecture/ModelArchitectureDiagram.xml
  JokesOnYou.sln
Labels: documentation

#102 Devops/93 update skeleton
  Server/JokesOnYou.Web.Api/Controllers/FlagController.cs
  Server/JokesOnYou.Web.Api/Controllers/JokesController.cs
  Server/JokesOnYou.Web.Api/Controllers/LikedJokeController.cs
  Server/JokesOnYou.Web.Api/Controllers/LikedTagsController.cs
  Server/JokesOnYou.Web.Api/Controllers/ReasonController.cs
  Server/JokesOnYou.Web.Api/Controllers/SavedJokeController.cs
  Server/JokesOnYou.Web.Api/Controllers/TagController.cs
  Server/JokesOnYou.Web.Api/DTOs/FlagCreateDto.cs
  Server/JokesOnYou.Web.Api/DTOs/FlagReplyDto.cs
  Server/JokesOnYou.Web.Api/DTOs/JokeCreateDto.cs
  Server/JokesOnYou.Web.Api/DTOs/JokeReplyDto.cs
  Server/JokesOnYou.Web.Api/DTOs/LikedJokeCreateDto.cs
  Server/JokesOnYou.Web.Api/DTOs/LikedJokeReplyDto.cs
  Server/JokesOnYou.Web.Api/DTOs/LikedTagsCreateDto.cs
  Server/JokesOnYou.Web.Api/DTOs/LikedTagsReplyDto.cs
  Server/JokesOnYou.Web.Api/DTOs/ReasonCreateDto.cs
  Server/JokesOnYou.Web.Api/DTOs/ReasonReplyDto.cs
  Server/JokesOnYou.Web.Api/DTOs/SavedJokeCreateDto.cs
  Server/JokesOnYou.Web.Api/DTOs/SavedJokeReplyDto.cs
  Server/JokesOnYou.Web.Api/DTOs/TagCreateDto.cs
  Server/JokesOnYou.Web.Api/DTOs/TagReplyDto.cs
  Server/JokesOnYou.Web.Api/Models/Flag.cs
  Server/JokesOnYou.Web.Api/Models/LikedJoke.cs
  Server/JokesOnYou.Web.Api/Models/LikedTags.cs
  Server/JokesOnYou.Web.Api/Models/Reason.cs
  Server/JokesOnYou.Web.Api/Models/SavedJoke.cs
  Server/JokesOnYou.Web.Api/Models/Tag.cs
  Server/JokesOnYou.Web.Api/Repositories/FlagRepository.cs
  Server/JokesOnYou.Web.Api/Repositories/Interfaces/IFlagRepository.cs
  Server/JokesOnYou.Web.Api/Repositories/Interfaces/IJokesRepository.cs
  Server/JokesOnYou.Web.Api/Repositories/Interfaces/ILikedJokeRepository.cs
  Server/JokesOnYou.Web.Api/Repositories/Interfaces/ILikedTagsRepository.cs
  Server/JokesOnYou.Web.Api/Repositories/Interfaces/IReasonRepository.cs
  Server/JokesOnYou.Web.Api/Repositories/Interfaces/ISavedJokeRepository.cs
  Server/JokesOnYou.Web.Api/Repositories/Interfaces/ITagRepository.cs
  Server/JokesOnYou.Web.Api/Repositories/JokesRepository.cs
  Server/JokesOnYou.Web.Api/Repositories/LikedJokeRepository.cs
  Server/JokesOnYou.Web.Api/Repositories/LikedTagsRepository.cs
  Server/JokesOnYou.Web.Api/Repositories/ReasonRepository.cs
  Server/JokesOnYou.Web.Api/Repositories/SavedJokeRepository.cs
  Server/JokesOnYou.Web.Api/Repositories/TagRepository.cs
  Server/JokesOnYou.Web.Api/Services/FlagService.cs
  Server/JokesOnYou.Web.Api/Services/Interfaces/IFlagService.cs
  Server/JokesOnYou.Web.Api/Services/Interfaces/IJokesService.cs
  Server/JokesOnYou.Web.Api/Services/Interfaces/ILikedJokeService.cs
  Server/JokesOnYou.Web.Api/Services/Interfaces/ILikedTagsService.cs
  Server/JokesOnYou.Web.Api/Services/Interfaces/IReasonService.cs
  Server/JokesOnYou.Web.Api/Services/Interfaces/ISavedJokeService.cs
  Server/JokesOnYou.Web.Api/Services/Interfaces/ITagService.cs
  Server/JokesOnYou.Web.Api/Services/JokesService.cs
  Server/JokesOnYou.Web.Api/Services/LikedJokeService.cs
  Server/JokesOnYou.Web.Api/Services/LikedTagsService.cs
  Server/JokesOnYou.Web.Api/Services/ReasonService.cs
  Server/JokesOnYou.Web.Api/Services/SavedJokeService.cs
  Server/JokesOnYou.Web.Api/Services/TagService.cs
Labels: devops

#99 57 feature create account controller2
  Server/JokesOnYou.Web.Api/Controllers/AccountController.cs
  Server/JokesOnYou.Web.Api/Exceptions/AppException.cs
  Server/JokesOnYou.Web.Api/Services/Interfaces/IUserService.cs
  Server/JokesOnYou.Web.Api/Services/UserService.cs
Labels: backend
